- name: "Register the md5 of ~/.bashrc before init for  {{ user }}"
  become: true
  become_user: "{{ user }}"
  ansible.builtin.stat:
    path: ~/.bashrc
    get_md5: true
  register: bashrc_stat_before

- name: Initialize the environment
  become: true
  become_user: "{{ user }}"
  ansible.builtin.command: "micromamba shell init --shell=bash --prefix={{ prefix }}"
  changed_when: false

- name: "Register the md5 of ~/.bashrc after init for {{ user }}"
  become: true
  become_user: "{{ user }}"
  ansible.builtin.stat:
    path: ~/.bashrc
    get_md5: true
  register: bashrc_stat_after

- name: Check whether or not initialization altered ~/.bashrc
  ansible.builtin.debug:
    msg: "Before: {{ bashrc_stat_before.stat.md5 | default('None') }}, After: {{ bashrc_stat_after.stat.md5 }}."
  changed_when: (not bashrc_stat_before.stat.exists) or ( bashrc_stat_before.stat.md5 != bashrc_stat_after.stat.md5 )

- name: Test {{ test_command }}
  become: true
  become_user: "{{ user }}"
  ansible.builtin.command: 'bash -i -c "micromamba activate; {{ test_command }}"'
  changed_when: false
