galaxy_info:
  role_name: slurm
  namespace: galaxyproject
  author: The Galaxy Project
  description: Install and manage the Slurm Workload Manager
  company: The Galaxy Project
  license: MIT
  min_ansible_version: 2.5
  github_branch: main
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - cluster
    - hpc
    - slurm
dependencies: []
