---

- name: Check munge dir
  ansible.builtin.file:
    path: /etc/munge
    owner: munge
    group: munge
    mode: 0700
    state: directory

- name: Install munge key
  ansible.builtin.copy:
    src: "{{ slurm_munge_key }}"
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: 0400
  when: slurm_munge_key is defined
  notify:
    - Restart munge

- name: Ensure Munge is enabled and running
  ansible.builtin.service:
    name: munge
    enabled: true
    state: started
